### PR TITLE
Edits to update formatting and match interface changes, 

### PR DESCRIPTION
**Pull request by clifford-smith**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Review by TJGitHubUser — COMMENTED** [review]
LAB_AK_02
Exercise 2, Task 3, Step 2, Table 1 - typo: "Create a new resopurse group..." Should say "resource."

**Review by TJGitHubUser — COMMENTED** [review]
Exercise 1, Task 3, Step 6. Is there an additional "shut down" at the end of this step? Or, is there possibly a period missing somewhere. It doesn't quite read correctly. Maybe the period comes right before "In the Shut Down Machine prompt select Shut Down...?"

**Comment by TJGitHubUser** [comment]
General question: I see all the changes are in the Lab answer key documents. Are you matching any changes you make there to what's in the equivalent docs with only the high level steps? For example, in Instructions/Labs/LAB_AK_02_Using_Windows_Admin_Center_in_hybrid_scenarios.md, have you checked LAB_AK_02_Using_Windows_Admin_Center_in_hybrid_scenarios.md?

I noticed that all the changes are in the LAK versions of the documents, which is why I'm asking.

Thanks!

**Comment by TJGitHubUser** [comment]
Thanks!

**Comment by clifford-smith** [comment]
> Exercise 1, Task 3, Step 6. Is there an additional "shut down" at the end of this step? Or, is there possibly a period missing somewhere. It doesn't quite read correctly. Maybe the period comes right before "In the Shut Down Machine prompt select Shut Down...?"

Which module is the step above in?

**Comment by clifford-smith** [comment]
> General question: I see all the changes are in the Lab answer key documents. Are you matching any changes you make there to what's in the equivalent docs with only the high level steps? For example, in Instructions/Labs/LAB_AK_02_Using_Windows_Admin_Center_in_hybrid_scenarios.md, have you checked LAB_AK_02_Using_Windows_Admin_Center_in_hybrid_scenarios.md?
> 
> I noticed that all the changes are in the LAK versions of the documents, which is why I'm asking.
> 
> Thanks!

No.

**Comment by TJGitHubUser** [comment]
Most students and instructors do use the LAK version of the lab instructions so making changes there makes sense. Many of the chnages in the last pull request are mainly formatting and minor (typos, rewording for clarification). I would say that if you find a major change in the LAK it would be good in future to cross reference the high level instructions just to make sure that changes doesn't need to be made. This would only be in the case where the instruction would be wrong or misleading in the high level instructions. So my guidance would be to only check in those instances where a major change is called for. In many instances, the LAK instruction is not even in the high level steps. Thanks...

**Comment by TJGitHubUser** [comment]
Sorry, it's in LAB_AK_04C_Implementing_SDN_ACL_by_using_Windows_Admin_Center.md.

Thanks!

**Pull request merged**
